[package]
name = "nova-game"
version = "0.1.0"
authors = ["Brennan Frydl <me@bfrydl.com>"]
edition = "2018"

[dependencies]
nova = { path = "../engine" }
serde = "1.0.78"
serde_derive = "1.0.78"
specs = "0.12.2"
specs-derive = "0.2.0"
bflog = "0.3.*"
winit = "0.17.2"
image = "0.20.1"
