[workspace]
exclude = ["nova", "tools/audino-import"]

[package]
name = "tvb"
version = "0.1.0"
authors = ["Brennan Frydl <me@bfrydl.com>"]
edition = "2018"

[profile.release]
lto = true

[dependencies]
nova = { path = "./nova" }
