[package]
name = "nova"
version = "0.2.0"
authors = ["Brennan Frydl <me@bfrydl.com>"]
edition = "2018"

[features]
default = []
headless = []

[dependencies]
chrono = "0.4"
crossbeam = "0.6"
derive_more = "0.13"
gfx-hal = "0.1"
log = { version = "0.4", features = ["std"] }
nalgebra = "*"
num-traits = "*"
rayon = "1.0"
shrev = "1.0"
specs = { git = "https://github.com/bfrydl/specs" }
specs-derive = "0.3"
winit = "0.18"
smallvec = "0.6.8"

[target.'cfg(all(unix, not(target_os = "macos")))'.dependencies]
gfx-backend-vulkan = "0.1"

[target.'cfg(windows)'.dependencies]
gfx-backend-dx12 = "0.1"

[target.'cfg(target_os = "macos")'.dependencies]
gfx-backend-metal = "0.1"
