[package]
name = "nova"
version = "0.1.0"
authors = ["Brennan Frydl <me@bfrydl.com>"]
edition = "2018"

[dependencies]
bflog = "0.3"
crossbeam = "0.4"
derive_more = "0.13"
gfx-hal = { version = "0.1", git = "https://github.com/gfx-rs/gfx", rev = "bd7f058efe78d7626a1cc6fbc0c1d3702fb6d2e7" }
gfx-memory = { version = "0.1", git = "https://github.com/gfx-rs/gfx-memory", rev = "1dacf31e26990c9636ba0f566ca8b02bcdd7e503" }
glsl-to-spirv = "0.1"
image = "0.20"
nalgebra = "0.16"
num-traits = "0.2"
quick-error = "1.2"
smallvec = "0.6"
specs = "0.14"
specs-derive = "0.3"
winit = "0.17"

[target.'cfg(all(unix, not(target_os = "macos")))'.dependencies]
gfx-backend-vulkan = { version = "0.1", git = "https://github.com/gfx-rs/gfx", rev = "bd7f058efe78d7626a1cc6fbc0c1d3702fb6d2e7" }

[target.'cfg(windows)'.dependencies]
gfx-backend-dx12 = { version = "0.1", git = "https://github.com/gfx-rs/gfx", rev = "bd7f058efe78d7626a1cc6fbc0c1d3702fb6d2e7" }

[target.'cfg(target_os = "macos")'.dependencies]
gfx-backend-metal = { version = "0.1", git = "https://github.com/gfx-rs/gfx", rev = "bd7f058efe78d7626a1cc6fbc0c1d3702fb6d2e7" }
