[package]
name = "nova"
version = "0.1.0"
authors = ["Brennan Frydl <me@bfrydl.com>"]
edition = "2018"

[dependencies]
ggez = { git = "https://gitlab.com/bfrydl/ggez.git", branch = "devel" }
nalgebra = "0.16.1"
specs = "0.12.2"
serde = "1.0.78"
serde_yaml = "0.8.3"
serde_derive = "1.0.78"
specs-derive = "0.2.0"
image = "0.19.0"
crossbeam-channel = "0.2.6"
gfx-hal = { git = "https://github.com/gfx-rs/gfx", features = ["serde"] }
winit = "0.17"
quick-error = "1.2.2"
smallvec = "0.6.5"
bflog = "0.2.2"
glsl-to-spirv = "*"

[target.'cfg(all(unix, not(target_os = "macos")))'.dependencies]
gfx-backend-vulkan = { git = "https://github.com/gfx-rs/gfx" }

[target.'cfg(windows)'.dependencies]
gfx-backend-dx12 = { git = "https://github.com/gfx-rs/gfx"}

[target.'cfg(target_os = "macos")'.dependencies]
gfx-backend-metal = { git = "https://github.com/gfx-rs/gfx"}
