[package]
name = "nova_graphics"
version = "0.3.0"
authors = ["Brennan Frydl <me@bfrydl.com>"]
edition = "2018"

[dependencies]
image = "0.21"
nova_core = { path = "../nova_core" }
nova_math = { path = "../nova_math" }
