[package]
name = "nova_log"
version = "0.1.0"
authors = ["Brennan Frydl <me@bfrydl.com>"]
edition = "2018"

[dependencies]
nova_sync = { path = "../nova_sync" }
lazy_static = "1.3"
slog = "2.4"
slog-async = "2.3"
slog-scope = "4.1.1"
slog-stdlog = "3.0"
slog-term = "2.4"
