[package]
name = "nova-audino-import"
version = "0.1.0"
authors = ["Brennan Frydl <me@bfrydl.com>"]
edition = "2018"

[dependencies]
nova = { path = "../../engine" }
nova-game = { path = "../../game" }
clap = "2.32.0"
serde_derive = "1.0.79"
serde-xml-rs = "0.2.1"
serde = "1.0.79"
