[package]
name = "nova_window"
version = "0.3.0"
authors = ["Brennan Frydl <me@bfrydl.com>"]
edition = "2018"

[dependencies]
nova_core = { path = "../nova_core" }
winit = { version = "0.18", features = ["serde"] }
