[package]
name = "nova_window"
version = "0.3.0"
authors = ["Brennan Frydl <me@bfrydl.com>"]
edition = "2018"

[dependencies]
gfx-hal = "0.1"
nova_core = { path = "../nova_core" }
nova_graphics = { path = "../nova_graphics" }
winit = { version = "0.18", features = ["serde"] }

