[package]
name = "nova_window"
version = "0.3.0"
authors = ["Brennan Frydl <me@bfrydl.com>"]
edition = "2018"

[dependencies]
crossbeam-channel = "0.3"
nova_math = { path = "../nova_math" }
winit = { version = "0.19", features = ["serde"] }
