[package]
name = "nova_input"
version = "0.3.0"
authors = ["Brennan Frydl <me@bfrydl.com>"]
edition = "2018"

[dependencies]
gilrs = "0.7"
nova_core = { path = "../nova_core" }
nova_window = { path = "../nova_window" }
uuid = "0.7"
